name: Deploy Strapi ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get ECR repo URL
        id: ecr
        run: |
          ECR_URL=$(terraform -chdir=terraform output -raw ecr_repo_url)
          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $ECR_URL:latest ./app

      - name: Push Docker image
        run: docker push $ECR_URL:latest

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
